variables:
  MONO_VERSION: 6_4_0
  NETCORE_VERSION: '3.0.x'
  XCODE_VERSION: 11.1

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Defines that a commit to the master branch should trigger this build
trigger:
- master

# Defines that PRs against this branch should also trigger this build
pr:
- master

# The type of machine this build should run on and what software should be on it
pool:
  vmImage: macos-10.14

# The different steps in our build
steps:

- bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
  displayName: Switch to the latest Xamarin SDK

- bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
  displayName: Switch to the latest Xcode

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk'
  inputs:
     version: $(NETCORE_VERSION)
     includePreviewVersions: false

- task: MSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: 'src/**/*.sln'
    msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false /p:PackageOutputPath=$(build.artifactstagingdirectory)'
    clean: true
